baseurl = "https://rdfzsz.pages.dev/"
#ä¸»é¢˜
languageCode = "zh-cn"
theme = "github-style"

#ç½‘ç«™æ˜¾ç¤ºåå­—
title = "RDFZ"
# home/category/tag é¡µé¢æ˜¾ç¤ºçš„æ–‡ç« æ•° (Default: 10)
paginate = 5
# home/category/tag é¡µé¢ç”¨äºæ‘˜è¦çš„å­—æ•° (Default: 70)
summaryLength = 50


[params]
  author = "stevessr"
  description = "powered by hugo "
  github = "stevessr"
  #facebook = "æ²¡æœ‰"
  #twitter = "æ²¡æœ‰"
  #linkedin = "æ²¡æœ‰"
  #instagram = "æ²¡æœ‰"
  #tumblr = "æ²¡æœ‰"
  email = "stevessrbackup@outlook.com"
  url = "https://rdfzsz.pages.dev/"
  keywords = "blog, google analytics"
  rss = true
  lastmod = true
  favicon = "/images/github.png"
  location = "China"
  userStatusEmoji = "ğŸ˜€"
  enableGitalk = true
  [params.sidebar]
    #Optional about block for sidebar (can be Markdown)
    about = "æˆ‘çš„åšå®¢[ç®€å•ç¤ºä¾‹](http://rdfzsz.pages.dev/)."
    # ä¾§è¾¹æ æ˜¾ç¤ºæœ€è¿‘å‡ æ¡æ–‡ç«  (Default: 5)
    num_recent_posts = 2

[params.gitalk]
    clientID = "1c50c2c8ad46e55c6f5a" # Your client ID
    clientSecret = "cebaca2492176bb7d6ee27dcfc415c5a0be48d97" # Your client secret
    repo = "realrdfz" # æ‚¨çš„åšå®¢çš„githubåœ°å€Repository nameï¼Œä¾‹å¦‚ï¼šxxxx.github.io
    owner = "rdfzsz" # æ‚¨çš„GitHub ID
    admin = "stevessrbackup" # æ‚¨çš„GitHub ID
    id = "location.pathname" # æ–‡ç« é¡µé¢çš„é“¾æ¥åœ°å€å°±æ˜¯ID
    labels = "gitalk" # Github issue labels. If you used to use Gitment, you can change it
    perPage = 15 # Pagination size, with maximum 100.
    pagerDirection = "last" # Comment sorting direction, available values are 'last' and 'first'.
    createIssueManually = true # è®¾ç½®ä¸ºtrueï¼Œå¦‚æœæ˜¯ç®¡ç†å‘˜ç™»å½•ï¼Œä¼šè‡ªåŠ¨åˆ›å»ºissueï¼Œå¦‚æœæ˜¯falseï¼Œéœ€è¦ç®¡ç†å‘˜æ‰‹åŠ¨æ·»åŠ ç¬¬ä¸€ä¸ªè¯„è®º(issue)
    distractionFreeMode = false # Enable hot key (cmd|ctrl + enter) submit comment.    
    proxy = "https://broken-wind-958e.29847163406422.workers.dev/https://github.com/login/oauth/access_token" # å¯ä»¥è‡ªè¡Œæ·»åŠ åå‘ä»£ç†
  [[params.links]]
    title = "Link"
    href = "https://github.com/rdfzsz"

[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":default"]